name: social_bucks
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>3.0.0 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  pin_code_fields: ^8.0.1
  dotted_border: ^2.1.0
  intl: ^0.18.0
  connectivity_plus: ^5.0.2
  get: ^4.6.6
  firebase_analytics: ^10.8.0
  devicelocale: ^0.7.0
  firebase_messaging: ^14.7.5
  firebase_database: ^10.2.4
  cloud_functions: ^4.4.2
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  loading_animation_widget: ^1.2.1
  beautiful_soup_dart: 
    git:
        url: https://github.com/cengizili/beautiful_soup_dart
        ref: master
  pinput: ^4.0.0
  purchases_flutter: ^6.26.0
  firebase_crashlytics: ^3.5.1
  linkfive_purchases: ^3.0.1
  flutter_local_notifications: ^17.0.0
  auto_localization: ^2.0.2
  auto_size_text: ^3.0.0
  firebase_storage: ^11.7.1
  image: ^4.1.7
  crypto: ^3.0.3
  hive_generator: ^2.0.1
  dartz: ^0.10.1
  shimmer: ^3.0.0
  url_launcher: ^6.3.0
  iban: ^1.0.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  collection: ^1.18.0
  random_avatar: ^0.0.8
  android_intent_plus: ^5.0.2
  flutter_inappwebview: ^6.0.0
  uuid: ^4.4.0
  firebase_remote_config: ^4.4.7
  package_info_plus: ^4.2.0
dependency_overrides:
  in_app_purchase: ^3.1.8
  http: ^0.13.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Plus Jakarta Sans
      fonts: 
        - asset: assets/fonts/PlusJakartaSansBold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSansSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSansMedium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSansRegular.ttf
          weight: 400
