// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARlB-QLz4EoLO3v4vD_XfiwmVwgs2yiCI',
    appId: '1:840516744035:android:f2129f71871e53c2b0d956',
    messagingSenderId: '840516744035',
    projectId: 'katchiu-fa0ab',
    databaseURL: 'https://katchiu-fa0ab-default-rtdb.firebaseio.com',
    storageBucket: 'katchiu-fa0ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALQ2wXv6YC0EFCAiU4d-pl30kIygzAOlY',
    appId: '1:840516744035:ios:f325a1385d4fea6ab0d956',
    messagingSenderId: '840516744035',
    projectId: 'katchiu-fa0ab',
    databaseURL: 'https://katchiu-fa0ab-default-rtdb.firebaseio.com',
    storageBucket: 'katchiu-fa0ab.appspot.com',
    androidClientId: '840516744035-i6tb6mkmetc0af3q7jhm06sktlnv4969.apps.googleusercontent.com',
    iosClientId: '840516744035-k9jjov0d45ieophatopinmte6ht6p6ev.apps.googleusercontent.com',
    iosBundleId: 'com.socialbucks.app',
  );

}